name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.2, 8.3, 8.4 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, mbstring

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR12 src tests

      - name: Run PHPUnit with coverage
        run: |
          mkdir -p coverage
          vendor/bin/phpunit --colors=always --coverage-clover=coverage/clover.xml

      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-coverage-${{ matrix.php }}
          path: coverage/clover.xml
